# Generated by Django 4.1.7 on 2023-03-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('english_name', models.CharField(max_length=50)),
                ('scientific_name', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('morphology', models.TextField()),
                ('image', models.ImageField(upload_to='mainImages/')),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
                'db_table': 'plants',
            },
        ),
    ]
