# Generated by Django 4.1.7 on 2023-05-29 19:49

import detail.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persian_name', models.CharField(max_length=100, null=True, verbose_name='Persian Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=detail.models.set_model_path, verbose_name='Image')),
                ('scientific_name', models.CharField(max_length=100, null=True, verbose_name='scientific Name')),
                ('family', models.CharField(max_length=100, null=True, verbose_name='Family')),
                ('morphology', models.TextField(null=True, verbose_name='Morphology')),
                ('flowering_time', models.CharField(max_length=200, null=True, verbose_name='flowering Time')),
                ('geographical_distribution', models.CharField(max_length=200, null=True, verbose_name='Geographical Distribution')),
                ('ecology', models.CharField(max_length=300, null=True, verbose_name='Ecology')),
                ('medicinal_properties', models.CharField(max_length=100, null=True, verbose_name='Medicinal Properties')),
                ('habitat_characteristics', models.CharField(max_length=200, null=True, verbose_name='Habitat')),
                ('climate', models.CharField(max_length=200, null=True, verbose_name='Climate')),
                ('soil_characteristics', models.CharField(max_length=200, null=True, verbose_name='Soil Characteristics')),
                ('more_info', models.TextField(blank=True, null=True, verbose_name='More Information')),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
                'db_table': 'plants',
            },
        ),
        migrations.CreateModel(
            name='Stem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=detail.models.set_stem_image_path)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail.plant')),
            ],
            options={
                'verbose_name': 'stem',
                'verbose_name_plural': 'stems',
                'db_table': 'stem_image',
            },
        ),
        migrations.CreateModel(
            name='Leaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=detail.models.set_leaf_image_path)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail.plant')),
            ],
            options={
                'verbose_name': 'leaf',
                'verbose_name_plural': 'leafs',
                'db_table': 'leaf_images',
            },
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=detail.models.set_flower_image_path)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail.plant')),
            ],
            options={
                'verbose_name': 'flower',
                'verbose_name_plural': 'flowers',
                'db_table': 'flower_images',
            },
        ),
    ]
