# Generated by Django 4.1.7 on 2023-03-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mainImages/')),
                ('name', models.CharField(max_length=50)),
                ('english_name', models.CharField(blank=True, max_length=50, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=50, null=True)),
                ('family', models.CharField(blank=True, max_length=50, null=True)),
                ('morphology', models.TextField(blank=True, null=True)),
                ('water_need', models.CharField(blank=True, max_length=50, null=True)),
                ('soil_need', models.CharField(blank=True, max_length=50, null=True)),
                ('salinity_tolerance', models.CharField(blank=True, max_length=50, null=True)),
                ('temperature_tolerance', models.CharField(blank=True, max_length=50, null=True)),
                ('species_score', models.CharField(blank=True, max_length=50, null=True)),
                ('first_planting_priority', models.CharField(blank=True, max_length=50, null=True)),
                ('second_planting_priority', models.CharField(blank=True, max_length=50, null=True)),
                ('third_planting_priority', models.CharField(blank=True, max_length=50, null=True)),
                ('suitable_planting_location', models.CharField(blank=True, max_length=50, null=True)),
                ('suitable_planting_combination', models.CharField(blank=True, max_length=50, null=True)),
                ('specific_characteristic', models.CharField(blank=True, max_length=50, null=True)),
                ('more_information', models.CharField(blank=True, max_length=50, null=True)),
                ('references', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
                'db_table': 'plants',
            },
        ),
    ]
