# Generated by Django 4.1.7 on 2023-06-08 18:43

import detail.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Property Name')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'db_table': 'medicines',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persian_name', models.CharField(max_length=100, null=True, unique=True, verbose_name='Persian Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=detail.models.set_model_path, verbose_name='Image')),
                ('scientific_name', models.CharField(max_length=100, null=True, unique=True, verbose_name='scientific Name')),
                ('family', models.TextField(null=True, verbose_name='Family')),
                ('morphology', models.TextField(null=True, verbose_name='Morphology')),
                ('flowering_time', models.TextField(null=True, verbose_name='flowering Time')),
                ('geographical_distribution', models.TextField(null=True, verbose_name='Geographical Distribution')),
                ('ecology', models.TextField(null=True, verbose_name='Ecology')),
                ('habitat_characteristics', models.TextField(null=True, verbose_name='Habitat')),
                ('climate', models.TextField(null=True, verbose_name='Climate')),
                ('soil_characteristics', models.TextField(null=True, verbose_name='Soil Characteristics')),
                ('more_info', models.TextField(blank=True, null=True, verbose_name='More Information')),
                ('video_iframe_link', models.URLField(blank=True, null=True)),
                ('adder_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adding_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
                'db_table': 'plants',
            },
        ),
        migrations.CreateModel(
            name='Stem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=detail.models.set_stem_image_path)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stem_image_set', to='detail.plant')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_stem_image_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'stem',
                'verbose_name_plural': 'stems',
                'db_table': 'stem_image',
            },
        ),
        migrations.CreateModel(
            name='MedicinalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_unit', to='detail.medicine')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_unit', to='detail.plant')),
            ],
            options={
                'verbose_name': 'medicinal unit',
                'verbose_name_plural': 'medicinal units',
                'db_table': 'medicinal_unit',
            },
        ),
        migrations.CreateModel(
            name='Leaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=detail.models.set_leaf_image_path)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaf_image_set', to='detail.plant')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_leaf_image_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'leaf',
                'verbose_name_plural': 'leafs',
                'db_table': 'leaf_images',
            },
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=detail.models.set_flower_image_path)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flower_image_set', to='detail.plant')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_flower_image_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'flower',
                'verbose_name_plural': 'flowers',
                'db_table': 'flower_images',
            },
        ),
    ]
