# Generated by Django 4.1.7 on 2023-05-30 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flower_image_set', to='detail.plant'),
        ),
        migrations.AlterField(
            model_name='leaf',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaf_image_set', to='detail.plant'),
        ),
        migrations.AlterField(
            model_name='stem',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stem_image_set', to='detail.plant'),
        ),
    ]
