# Generated by Django 4.1.7 on 2023-03-16 11:24

import detail.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_alter_plant_english_name_alter_plant_family_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='image',
            new_name='main_image',
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=detail.models.get_file_path)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail.plant')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'db_table': 'videos',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=detail.models.get_file_path)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail.plant')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'images',
            },
        ),
    ]
