# Generated by Django 4.1.7 on 2023-06-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_alter_flower_plant_alter_leaf_plant_alter_stem_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='video_iframe_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
