# Generated by Django 4.1.7 on 2023-03-19 17:04

import detail.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0003_rename_image_plant_main_image_video_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=detail.models.get_file_path),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
