# Generated by Django 4.1.7 on 2023-06-05 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0003_plant_video_iframe_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flower',
            old_name='image',
            new_name='flower_image',
        ),
        migrations.RenameField(
            model_name='leaf',
            old_name='image',
            new_name='leaf_image',
        ),
        migrations.RenameField(
            model_name='stem',
            old_name='image',
            new_name='stem_image',
        ),
    ]
