# Generated by Django 4.1.7 on 2023-06-11 15:05

import detail.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detail', '0003_plant_editor_user_alter_medicinalunit_medicine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=detail.models.set_habitat_image_path)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitat_image_set', to='detail.plant')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_habitat_image_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'habitat',
                'verbose_name_plural': 'habitats',
                'db_table': 'habitat_images',
            },
        ),
    ]
