# Generated by Django 4.1.7 on 2023-06-12 09:42

import detail.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0004_habitat'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='info_file',
            field=models.FileField(blank=True, upload_to=detail.models.set_model_info_file, verbose_name='Information File'),
        ),
        migrations.AddField(
            model_name='plant',
            name='per_path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
