# Generated by Django 4.1.7 on 2023-06-07 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detail', '0005_rename_flower_image_flower_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='medicinal_properties',
        ),
        migrations.AddField(
            model_name='flower',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_flower_image_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaf',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_leaf_image_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plant',
            name='adder_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adding_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_stem_image_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Property Name')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines_properties', to='detail.plant')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'db_table': 'medicines',
            },
        ),
    ]
