# Generated by Django 4.1.7 on 2023-06-07 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detail', '0006_remove_plant_medicinal_properties_flower_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_flower_image_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaf',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_leaf_image_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_stem_image_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
