# Generated by Django 4.1.7 on 2023-06-27 07:26

import detail.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detail', '0007_alter_plant_persian_name_alter_plant_scientific_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=detail.models.set_habitat_image_path)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruit_image_set', to='detail.plant')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_fruit_image_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fruit',
                'verbose_name_plural': 'fruits',
                'db_table': 'fruit_images',
            },
        ),
    ]
