# Generated by Django 4.1.7 on 2023-06-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0007_alter_flower_user_alter_leaf_user_alter_stem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='climate',
            field=models.TextField(null=True, verbose_name='Climate'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='ecology',
            field=models.TextField(null=True, verbose_name='Ecology'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='family',
            field=models.TextField(null=True, verbose_name='Family'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='flowering_time',
            field=models.TextField(null=True, verbose_name='flowering Time'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='geographical_distribution',
            field=models.TextField(null=True, verbose_name='Geographical Distribution'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='habitat_characteristics',
            field=models.TextField(null=True, verbose_name='Habitat'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='persian_name',
            field=models.TextField(null=True, verbose_name='Persian Name'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='scientific_name',
            field=models.TextField(null=True, verbose_name='scientific Name'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='soil_characteristics',
            field=models.TextField(null=True, verbose_name='Soil Characteristics'),
        ),
    ]
