# Generated by Django 4.1.7 on 2023-06-28 08:04

import detail.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0008_fruit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='image',
            field=models.ImageField(upload_to=detail.models.set_fruit_image_path),
        ),
    ]
